language: generic

group: edge

dist: trusty

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- make
- git diff --exit-code
- git diff --cached --exit-code
- ./runtests
- TMPL=$(git log -1 | awk '/BUILD packer-template.*json/ { print $NF }')
- if [[ $TMPL ]] ; then packer build -only=docker ${TMPL} ; fi
